title = "Piledog"
description = "扯蛋"

base_url = "https://piledog.github.io/"

compile_sass = true
minify_html = false

taxonomies = [
  {name = "tag"}
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]